import { describe, expect, it } from 'vitest';

import { computeMerkleRoot, leafHash, verifyMerkleProof } from '../src/merkle';
import { verifyWinners, WINNER_SNAPSHOT_SCHEMA, type WinnerSnapshotV1 } from '../src/winners';
import fixture from './fixtures/merkle-backend.json';

/**
 * fixtures/merkle-backend.json is the output of the BACKEND's buildMerkleTree
 * (api/src/server/services/escrow/merkle.ts), regenerated by
 * scripts/make-merkle-fixture.ts. Every assertion here is "the SDK agrees with
 * what the finaliser publishes".
 */
type Hex = `0x${string}`;

describe('merkle vs the backend builder', () => {
  for (const name of ['five', 'single'] as const) {
    const tree = fixture[name];

    it(`${name}: recomputes the backend root from the inputs, in any order`, () => {
      expect(computeMerkleRoot(tree.input)).toBe(tree.root);
      expect(computeMerkleRoot([...tree.input].reverse())).toBe(tree.root);
    });

    it(`${name}: recomputes every leaf hash`, () => {
      for (const value of tree.dump.values) expect(leafHash(value.account, value.amount)).toBe(value.leaf);
    });

    it(`${name}: verifies every backend proof and rejects a wrong amount`, () => {
      for (const entry of tree.entries) {
        expect(verifyMerkleProof(tree.root as Hex, entry.account, entry.amount, entry.proof as Hex[])).toBe(true);
        expect(verifyMerkleProof(tree.root as Hex, entry.account, BigInt(entry.amount) + 1n, entry.proof as Hex[])).toBe(false);
      }
    });
  }

  it('refuses duplicates, zero and JS-number-looking amounts', () => {
    const a = fixture.five.input[0];
    expect(() => computeMerkleRoot([a, a])).toThrow(/more than once/);
    expect(() => leafHash(a.account, '0')).toThrow();
    expect(() => leafHash(a.account, '1e18')).toThrow();
    expect(() => computeMerkleRoot([])).toThrow();
  });
});

/** A "winner snapshot v1" built from the backend tree exactly as snapshot.ts lays it out. */
const snapshotFrom = (overrides: Partial<WinnerSnapshotV1> = {}): WinnerSnapshotV1 => {
  const tree = fixture.five;
  const leaves = [...tree.dump.values]
    .sort((a, b) => a.treeIndex - b.treeIndex)
    .map((value) => ({ account: value.account, amount: value.amount, leaf: value.leaf as Hex }));
  const amounts = tree.input.map((entry) => entry.amount);
  const total = amounts.reduce((sum, amount) => sum + BigInt(amount), 0n).toString();
  return {
    schema: WINNER_SNAPSHOT_SCHEMA,
    chainId: 8453,
    escrow: '0x16267bE6D067b3d411bf779B5aD041f9eba4CadE',
    questId: '0xa15bc60c955c405d20d9149c709e2460f1c2d9a497496a7f46004d1772c3054c',
    quest: { loyaltyProjectId: 1, linkTitle: 'base-launch-run-quest', type: 'scoreboard', endAt: null, threshold: null },
    asset: { token: '0x0000000000000000000000000000000000000000', native: true, decimals: 18 },
    funded: '400000000000000',
    totalAllocated: total,
    rules: {
      ranking: 'test',
      tiers: [
        { rewardId: 1, startPlace: 1, endPlace: 3, amount: '100000000000000' },
        { rewardId: 2, startPlace: 4, endPlace: 4, amount: '70000000000000' },
        { rewardId: 3, startPlace: 5, endPlace: 5, amount: '30000000000000' },
      ],
    },
    scoreboard: [1, 2, 3, 4, 5].map((place) => ({
      place,
      points: String(100 - place),
      tieBreak: null,
      amount: place <= 3 ? '100000000000000' : place === 4 ? '70000000000000' : '30000000000000',
    })),
    merkle: { format: 'peddles-quest-escrow-merkle-v1', encoding: {}, leaves, root: tree.root as Hex },
    ...overrides,
  };
};

const chainClient = (pool: Partial<Record<string, unknown>>, chainId = 8453) =>
  ({
    getChainId: async () => chainId,
    readContract: async () => ({
      creator: '0x31fffDFc9Ec36F1340be49245E1c96F4512F679e',
      rewardToken: '0x0000000000000000000000000000000000000000',
      funded: 400000000000000n,
      claimed: 0n,
      claimsOpenAt: 1n,
      claimDeadline: 2n,
      merkleRoot: fixture.five.root,
      finalised: true,
      swept: false,
      ...pool,
    }),
  }) as never;

describe('verifyWinners', () => {
  it('MATCH against the on-chain root', async () => {
    const result = await verifyWinners(snapshotFrom(), chainClient({}));
    expect(result.failures).toEqual([]);
    expect(result.match).toBe(true);
    expect(result.computedRoot).toBe(fixture.five.root);
    expect(result.referenceSource).toBe('chain');
    expect(result.totalAllocated).toBe(400000000000000n);
  });

  it('accepts JSON text and an offline root', async () => {
    const result = await verifyWinners(JSON.stringify(snapshotFrom()), null, { root: fixture.five.root as Hex });
    expect(result.match).toBe(true);
    expect(result.referenceSource).toBe('supplied');
  });

  it('MISMATCH when the chain holds a different root, or is not finalised', async () => {
    const other = await verifyWinners(snapshotFrom(), chainClient({ merkleRoot: fixture.single.root }));
    expect(other.match).toBe(false);
    expect(other.failures.join('\n')).toMatch(/on-chain root/);

    const open = await verifyWinners(snapshotFrom(), chainClient({ finalised: false }));
    expect(open.failures.join('\n')).toMatch(/NOT finalised/);
  });

  it('MISMATCH when a leaf amount is edited', async () => {
    const snapshot = snapshotFrom();
    snapshot.merkle.leaves[0] = { ...snapshot.merkle.leaves[0], amount: '100000000000001' };
    const result = await verifyWinners(snapshot, chainClient({}));
    expect(result.match).toBe(false);
  });

  it('MISMATCH when a place earned more than its tiers', async () => {
    const snapshot = snapshotFrom();
    snapshot.scoreboard[4] = { ...snapshot.scoreboard[4], amount: '70000000000000' };
    const result = await verifyWinners(snapshot, chainClient({}));
    expect(result.failures.join('\n')).toMatch(/tiers covering it/);
  });

  it('MISMATCH on the wrong chain', async () => {
    const result = await verifyWinners(snapshotFrom(), chainClient({}, 56));
    expect(result.failures.join('\n')).toMatch(/chain 56/);
  });

  it('checks a bafkrei CID against the fetched bytes', async () => {
    const { rawCidOf } = await import('../src/winners');
    const bytes = new TextEncoder().encode(JSON.stringify(snapshotFrom()));
    const cid = rawCidOf(bytes);
    const fetch = async () => ({ ok: true, status: 200, arrayBuffer: async () => bytes.buffer.slice(0) as ArrayBuffer });
    const result = await verifyWinners(`ipfs://${cid}`, chainClient({}), { fetch });
    expect(result.match).toBe(true);
    expect(result.notes[0]).toMatch(/content hash matches/);

    const tampered = async () => ({ ok: true, status: 200, arrayBuffer: async () => new TextEncoder().encode('{}').buffer as ArrayBuffer });
    await expect(verifyWinners(cid, chainClient({}), { fetch: tampered })).rejects.toThrow(/does not hash/);
  });
});
