#!/usr/bin/env node
/**
 * Writes src/abis.ts from the Foundry artifacts in ../contracts/out.
 *
 * Only the entries an integrator needs are kept (reads, the public user
 * actions, their events and errors). Owner-only setters are left out on
 * purpose: an SDK that makes `setDepositFeeBps` one autocomplete away invites
 * nobody but the Safe to call it, and the Safe does not use this package.
 *
 *   node scripts/extract-abis.mjs          # regenerate
 *   node scripts/extract-abis.mjs --check  # exit 1 if src/abis.ts is stale
 *
 * Reads ../contracts/out only; never runs forge.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../../contracts/out');
const target = resolve(here, '../src/abis.ts');

const KEEP = {
  PeddlesQuestEscrow: {
    functions: [
      'questOf', 'hasClaimed', 'verifyClaim', 'claim', 'outstanding', 'withdrawable', 'withdraw',
      'sweepExpired', 'createQuest', 'quoteDepositFee', 'depositFeeBps', 'creationFee', 'claimDelay',
      'unclaimedTreasuryBps', 'isRewardAsset', 'depositCapFor', 'maxQuestDeposit', 'entryPaused',
      'feeRouter', 'owner', 'isOperator', 'MAX_CREATION_FEE', 'MAX_DEPOSIT_FEE_BPS',
      'MAX_UNCLAIMED_TREASURY_BPS',
    ],
    events: ['QuestCreated', 'QuestFinalised', 'RewardClaimed', 'QuestSwept', 'Credited', 'Withdrawn', 'ClaimDeadlineExtended'],
    errors: 'all',
  },
  PeddlesPromotionMarket: {
    functions: ['slotOf', 'isActive', 'quote', 'pricePerDay', 'buyPlacement', 'entryPaused', 'MAX_DAYS', 'MAX_PRICE_PER_DAY', 'owner', 'feeRouter'],
    events: ['PlacementPurchased'],
    errors: 'all',
  },
  PeddlesQuestBadge: {
    functions: ['badgeOf', 'balanceOf', 'ownerOf', 'questOf', 'tokenURI', 'totalSupply', 'mint', 'mintFee', 'mintDigest', 'signer', 'locked', 'entryPaused', 'MAX_MINT_FEE', 'name', 'symbol', 'owner', 'feeRouter'],
    events: ['BadgeMinted', 'Transfer', 'Locked'],
    errors: 'all',
  },
  PeddlesFeeRouter: {
    functions: ['feeRoute', 'treasury', 'flywheel', 'flywheelBps', 'splitProtocolCut', 'owner'],
    events: ['TreasuryUpdated'],
    errors: 'all',
  },
};

/** Drop `internalType`: noise for viem's type inference, and churns with solc. */
const strip = (param) => {
  const next = { name: param.name, type: param.type };
  if (param.indexed !== undefined) next.indexed = param.indexed;
  if (param.components) next.components = param.components.map(strip);
  return next;
};

const pick = (abi, spec) => {
  const entries = [];
  for (const name of spec.functions) {
    const found = abi.filter((e) => e.type === 'function' && e.name === name);
    if (!found.length) throw new Error(`function ${name} not in artifact`);
    entries.push(...found);
  }
  for (const name of spec.events) {
    const found = abi.find((e) => e.type === 'event' && e.name === name);
    if (!found) throw new Error(`event ${name} not in artifact`);
    entries.push(found);
  }
  entries.push(...abi.filter((e) => e.type === 'error'));
  return entries.map((e) => {
    const next = { type: e.type, name: e.name, inputs: e.inputs.map(strip) };
    if (e.type === 'function') {
      next.outputs = e.outputs.map(strip);
      next.stateMutability = e.stateMutability;
    }
    if (e.type === 'event') next.anonymous = Boolean(e.anonymous);
    return next;
  });
};

const constName = (contract) =>
  contract.replace(/^Peddles/, 'peddles').replace(/^./, (c) => c.toLowerCase()) + 'Abi';

let body = `/**
 * GENERATED by scripts/extract-abis.mjs from contracts/out (Foundry artifacts).
 * Do not edit by hand: run \`npm run abis\` and commit the result.
 *
 * Minimal ABIs: the reads and public user actions an integrator needs, their
 * events, and every custom error (so a revert decodes to a name). Owner-only
 * setters are deliberately absent.
 */
`;

for (const [contract, spec] of Object.entries(KEEP)) {
  const artifact = JSON.parse(await readFile(resolve(out, `${contract}.sol/${contract}.json`), 'utf8'));
  const abi = pick(artifact.abi, spec);
  body += `\nexport const ${constName(contract)} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current.replace(/\r\n/g, '\n') !== body) {
    console.error('src/abis.ts is stale: run `npm run abis`');
    process.exit(1);
  }
  console.log('src/abis.ts matches contracts/out');
} else {
  await writeFile(target, body);
  console.log(`wrote ${target}`);
}
